@startuml
'https://plantuml.com/sequence-diagram

skin rose

package Bibliotech <<Folder>>{

    package Services <<Folder>>{

        Class SistemaImpl{
        +SistemaImpl()
        +main(args[]: String) void
        }

        Interface Sistema{
        +leerUsuarios(): void
        +leerLibros(): void
        +actualizarArchivo(List<Libros> var1): void
        }

    }
    package Model <<Folder>>{

        Class Usuario{
        - nombre
        - apellido
        - rut
        - contraseña
        + Get´s
        + Set´s

        }

        Class Libros{
        - isbn
        - nombreLibro
        - autor
        - categoria
        - cantPaginas
        - stock
        + Get´s
        + Set´s

        }
    }

    package Utils <<Folder>>{
        Class IniciarSesion{
        - private registerForm: JPanel ;
        - private passwordField1: JPasswordField;
        - private rutIniciar: JTextField;
        - private iniciarSesionButton: JButton;
        - private salirButton: JButton;
        - private panel1 JPanel;
        - private imagenlogo: JLabel;
        - private listaUsuario: List<Usuario>
        }

        Class menuPrincipal{
        -private devolverLibroButton:  JButton;
        -private menuPrincipal:  JPanel;
        -private buscarLibroButton:  JButton;
        -private agregarNuevoLibroButton:  JButton;
        -private prestarLibroButton:  JButton;
        -private listaUsuario List<Usuario>;
        }

        Class agregarLibro{
            -private JPanel registerForm;
            -private JTextField isbnInicial;
            -private JPanel agregarPanel;
            -private JTextField tituloInicial;
            -private JTextField autorInicial;
            -private JTextField categoriaInicial;
            -private JTextField copiasInicial;
            -private JTextField precioInicial;
            -private JButton buscarButton;
            -private JButton volverButton;
            -private List<Usuario> listaUsuario;
            -private List<Libros> listaLibros;
        }
        Class buscarLibro{

            -private List<Usuario> listaUsuario;
            -private List<Libros> listaLibros;
            -private JPanel registerForm;
            -private JButton buscarButton;
            -private JPanel buscar;
            -private JTextField isbnIniciar;
            -private JButton volverButton;
            -private JTextArea impresion;
        }
    }
    }
    SistemaImpl ..> Sistema
    SistemaImpl --> Usuario
    SistemaImpl --> Libros
    SistemaImpl --> menuPrincipal
    SistemaImpl --> agregarLibro
    SistemaImpl --> IniciarSesion
    SistemaImpl --> buscarLibro
}
@enduml